export const FETCH_AUTH_REQUEST = 'FETCH_AUTH_REQUEST';
export const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS';
export const FETCH_AUTH_FAILURE = 'FETCH_AUTH_FAILURE';
export const FETCH_AUTH = 'FETCH_AUTH';
export const LOAD_USER = 'LOAD_USER';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const FETCH_USERS = 'FETCH_USERS';

export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';

export const FETCH_SEND_MESSAGE_REQUEST = 'FETCH_SEND_MESSAGE_REQUEST';
export const FETCH_SEND_MESSAGE_SUCCESS = 'FETCH_SEND_MESSAGE_SUCCESS';
export const FETCH_SEND_MESSAGE_FAILURE = 'FETCH_SEND_MESSAGE_FAILURE';
export const FETCH_SEND_MESSAGE = 'FETCH_SEND_MESSAGE';

export const ADD_MESSAGE = 'ADD_MESSAGE';

export const FETCH_DIALOGS_REQUEST = 'FETCH_DIALOGS_REQUEST';
export const FETCH_DIALOGS_SUCCESS = 'FETCH_DIALOGS_SUCCESS';
export const FETCH_DIALOGS_FAILURE = 'FETCH_DIALOGS_FAILURE';
export const FETCH_DIALOGS = 'FETCH_DIALOGS';
